export const Strings = {
  app: {
    name: 'Zsebbank',
    version: '2.0.0',
  },
  tabs: {
    overview: 'Áttekintés',
    accounts: 'Számlák',
    newTransaction: 'Új',
    piggyBanks: 'Perselyek',
    more: 'Több',
  },
  dashboard: {
    title: 'Áttekintés',
    totalBalance: 'Teljes egyenleg',
    cash: 'Készpénz',
    digital: 'Digitális',
    monthlyIncome: 'Bevétel',
    monthlyExpense: 'Kiadás',
    monthlySummary: 'Havi összesítő',
    recentTransactions: 'Legutóbbi tranzakciók',
    upcomingRecurring: 'Közelgő ismétlődő',
    showAll: 'Összes',
    noTransactions: 'Még nincs tranzakció',
    noAccounts: 'Hozd létre az első számládat!',
  },
  account: {
    title: 'Számlák',
    addNew: 'Új számla',
    edit: 'Számla szerkesztése',
    name: 'Név',
    type: 'Típus',
    bank: 'Bankszámla',
    cashType: 'Készpénz',
    startingBalance: 'Kezdő egyenleg',
    balance: 'Egyenleg',
    icon: 'Ikon',
    color: 'Szín',
    deleteConfirm: 'Biztosan törölni szeretnéd ezt a számlát?',
    deleteWarning: 'A számlához tartozó tranzakciók is törlődnek.',
    totalAll: 'Összesen',
    totalCash: 'Készpénz összesen',
    totalBank: 'Számlák összesen',
  },
  transaction: {
    title: 'Tranzakció',
    addNew: 'Új tranzakció',
    edit: 'Tranzakció szerkesztése',
    income: 'Bevétel',
    expense: 'Kiadás',
    transfer: 'Átutalás',
    name: 'Megnevezés',
    amount: 'Összeg',
    date: 'Dátum',
    labels: 'Címkék',
    description: 'Leírás',
    account: 'Számla',
    fromAccount: 'Honnan?',
    toAccount: 'Hova?',
    available: 'Elérhető',
    preview: 'Előnézet',
    save: 'Mentés',
    deleteConfirm: 'Biztosan törölni szeretnéd ezt a tranzakciót?',
    history: 'Előzmények',
    noTransactions: 'Még nincs tranzakció',
    filterAll: 'Mind',
    search: 'Keresés...',
  },
  recurring: {
    title: 'Ismétlődő',
    addNew: 'Új ismétlődő',
    edit: 'Ismétlődő szerkesztése',
    frequency: 'Gyakoriság',
    monthly: 'Havonta',
    bimonthly: 'Kéthavonta',
    quarterly: 'Negyedévente',
    yearly: 'Évente',
    nextDue: 'Következő esedékesség',
    active: 'Aktív',
    inactive: 'Inaktív',
    startDate: 'Kezdő dátum',
    dueSoon: 'Hamarosan esedékes',
    noRecurring: 'Nincs ismétlődő tranzakció',
  },
  piggy: {
    title: 'Perselyek',
    addNew: 'Új persely',
    edit: 'Persely szerkesztése',
    name: 'Név',
    target: 'Célösszeg',
    noTarget: 'Nincs célösszeg',
    current: 'Jelenlegi összeg',
    linkedAccount: 'Kapcsolt számla',
    noLinked: 'Nincs kapcsolva',
    deposit: 'Befizetés',
    withdraw: 'Kivétel',
    fromAccount: 'Számláról',
    toAccount: 'Számlára',
    deleteConfirm: 'Biztosan törölni szeretnéd ezt a perselyt?',
    noPiggyBanks: 'Még nincs persely',
    progress: 'Haladás',
  },
  statistics: {
    title: 'Statisztikák',
    monthlyOverview: 'Havi áttekintés',
    byLabel: 'Címkék szerint',
    trend: 'Havi trend',
    balance: 'Egyenleg',
    noData: 'Nincs elég adat',
    difference: 'Különbség',
  },
  settings: {
    title: 'Beállítások',
    pin: 'PIN kód',
    pinSetup: 'PIN beállítása',
    pinChange: 'PIN módosítása',
    pinRemove: 'PIN törlése',
    pinEnter: 'Add meg a PIN kódot',
    pinNew: 'Adj meg egy új PIN kódot',
    pinConfirm: 'Erősítsd meg a PIN kódot',
    pinMismatch: 'A PIN kódok nem egyeznek',
    pinWrong: 'Hibás PIN kód',
    labels: 'Címkék kezelése',
    export: 'Adatok exportálása',
    import: 'Adatok importálása',
    importWarning: 'Az importálás felülírja az összes meglévő adatot!',
    about: 'Alkalmazás infó',
    exportSuccess: 'Adatok sikeresen exportálva!',
    importSuccess: 'Adatok sikeresen importálva!',
  },
  debt: {
    title: 'Tartozások',
    addNew: 'Új tartozás',
    edit: 'Tartozás szerkesztése',
    theyOweMe: 'Nekem tartoznak',
    iOweThem: 'Én tartozom',
    personName: 'Ki?',
    reason: 'Miért?',
    settle: 'Teljesítés',
    settled: 'Teljesítve',
    pending: 'Nyitott',
    settledOn: 'Teljesítve',
    settleAccount: 'Melyik számlára?',
    settleFromAccount: 'Melyik számláról?',
    deleteConfirm: 'Biztosan törölni szeretnéd ezt a tartozást?',
    deleteSettledWarning: 'A teljesített tartozás törlése visszafordítja az egyenleg-hatást.',
    noDebts: 'Nincs tartozás',
    totalOwedToMe: 'Nekem járó',
    totalIOwe: 'Tartozásom',
    all: 'Mind',
  },
  common: {
    save: 'Mentés',
    cancel: 'Mégse',
    delete: 'Törlés',
    edit: 'Szerkesztés',
    back: 'Vissza',
    confirm: 'Megerősítés',
    loading: 'Betöltés...',
    error: 'Hiba történt',
    success: 'Sikeres',
    yes: 'Igen',
    no: 'Nem',
    ft: 'Ft',
    optional: 'opcionális',
    noItems: 'Nincs elem',
  },
  onboarding: {
    welcome: 'Üdvözöl a Zsebbank!',
    subtitle: 'Kövesd nyomon a pénzügyeidet egyszerűen.',
    setupAccounts: 'Válaszd ki, hol tartod a pénzedet:',
    startingBalance: 'Kezdő egyenleg',
    setupPin: 'Szeretnél PIN kódot beállítani?',
    getStarted: 'Kezdjük!',
    skip: 'Kihagyás',
    next: 'Tovább',
  },
} as const;
